### ISSUE TITLE
PF

### ISSUE THREAD

**Issue by GenesisMauries** [RocioLV/DEV010-data-lovers#25]
# OAs

- [Funciones (params, args, return)](https://www.youtube.com/watch?v=5VVBrfWQ2Wk)
- [Diferenciar entre expresiones (expressions) y sentencias (statements)](https://medium.com/launch-school/javascript-expressions-and-statements-4d32ac9c0e74)
- [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [Validator HTML](https://validator.w3.org/)

**Comment by RocioLV** [comment]
Todo checado :)
